name: style

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Run Ruff linter
        run: |
          poetry run ruff --version
          poetry run ruff check --diff .

  formating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Run Ruff formatter
        run: |
          poetry run ruff --version
          poetry run ruff format --diff .

  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Run mypy 
        run: |
          poetry run mypy --version
          poetry run mypy app pyrorisks
